class AddNotNulls < ActiveRecord::Migration[6.1]
  def change
    change_column_null(:accounts, :name, false)
    change_column_null(:accounts_dishes, :account_id, false)
    change_column_null(:accounts_dishes, :dish_id, false)
    change_column_null(:accounts_grapes, :account_id, false)
    change_column_null(:accounts_grapes, :grape_id, false)
    change_column_null(:accounts_wines, :account_id, false)
    change_column_null(:accounts_wines, :wine_id, false)
    change_column_null(:countries, :name, false)
    change_column_null(:countries_wines, :country_id, false)
    change_column_null(:countries_wines, :wine_id, false)
    change_column_null(:dishes, :name, false)
    change_column_null(:grapes, :name, false)
    change_column_null(:grapes_wines, :grape_id, false)
    change_column_null(:grapes_wines, :wine_id, false)
    change_column_null(:producers, :name, false)
    change_column_null(:producers_wines, :producer_id, false)
    change_column_null(:producers_wines, :wine_id, false)
    change_column_null(:proteins, :name, false)
    change_column_null(:proteins_grapes, :protein_id, false)
    change_column_null(:proteins_grapes, :grape_id, false)
    change_column_null(:regions, :name, false)
    change_column_null(:regions, :country_id, false)
    change_column_null(:regions_wines, :region_id, false)
    change_column_null(:regions_wines, :wine_id, false)
    change_column_null(:sauces, :name, false)
    change_column_null(:sauces_grapes, :sauce_id, false)
    change_column_null(:sauces_grapes, :grape_id, false)
    change_column_null(:subregions, :name, false)
    change_column_null(:subregions, :region_id, false)
    change_column_null(:subregions_wines, :subregion_id, false)
    change_column_null(:subregions_wines, :wine_id, false)
    change_column_null(:users, :username, false)
    change_column_null(:users, :email, false)
    change_column_null(:users, :account_id, false)
    change_column_null(:wines, :name, false)
    change_column_null(:wines, :has_vintage, false)
    change_column_null(:wines_dishes, :wine_id, false)
    change_column_null(:wines_dishes, :dish_id, false)
    change_column_null(:wines_proteins, :wine_id, false)
    change_column_null(:wines_proteins, :protein_id, false)
    change_column_null(:wines_sauces, :sauce_id, false)
    change_column_null(:wines_sauces, :wine_id, false)
  end
end
